# Wrangler configuration for Cloudflare Pages
# Name must match the Cloudflare Pages project name
name = "pixelatad"
compatibility_date = "2024-09-23"

# Tell Wrangler this is a Pages project and where the build outputs
pages_build_output_dir = "./out"
